# Generated by Django 4.0.6 on 2022-07-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topping',
            name='ingredients',
            field=models.TextField(default=None),
        ),
    ]
