# Generated by Django 4.0.6 on 2022-07-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_toppings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Topping',
        ),
    ]
