# Generated by Django 4.0.6 on 2022-07-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_rename_toppings_topping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='name',
            new_name='ingredients',
        ),
    ]
