# Generated by Django 4.0.6 on 2022-07-27 18:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_alter_pizza_date_added_alter_pizza_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pizza',
            name='order',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topping',
            name='ingredients',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='topping',
            name='pizza',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='pizzas.pizza'),
            preserve_default=False,
        ),
    ]
