# Generated by Django 4.0.6 on 2022-07-20 18:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0004_rename_name_topping_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 20, 18, 46, 11, 21990, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
