# Generated by Django 4.0.6 on 2022-07-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_topping_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'toppings'},
        ),
    ]
