# Generated by Django 4.0.6 on 2022-07-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0005_alter_pizza_date_added_alter_pizza_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='order',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='topping',
            name='pizza',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pizzas.pizza'),
        ),
    ]
