# Generated by Django 4.0.6 on 2022-07-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0006_alter_topping_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={},
        ),
        migrations.RemoveField(
            model_name='topping',
            name='date_added',
        ),
    ]
